NAME            := <package_name>
PACKAGER        := 'John Doe <john.doe@example.com>'
VENDOR          := 'Example Corp.'
TARGET_DIR      := $(abspath target)
DISTS_DIR       := $(TARGET_DIR)/dists

#RPM_CHANGELOG   := rpm/changelog
#RPM_DEBUGINFO   := 0

include rpmMake/Makefile

.PHONY: all check fpm rpm_fpm

all: rpm
check: rpm_check

# It is possible to add any new section as long as they are not prefixed with `rpm_`
